services:
  react-app:
    build:
      context: .
    ports:
      - '8092:8092'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - json-server-1  
      - json-server-2

  json-server-1:
    image: node:20
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "5001:5001"
    command: >
      sh -c "npm install json-server && npx json-server --watch /app/fake_api_json/companies-lookup.json --port 5001"

  json-server-2:
    image: node:20
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "5002:5002"
    command: >
      sh -c "npm install json-server && npx json-server --watch /app/fake_api_json/securities.json --port 5002"
